apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sb-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-hello-world
    spec:
      containers:
      - name: sb-hello-world
        image: mtafougalti/sb-hello-world-image:0.0.6
        ports:
        - containerPort: 8090
